### PR TITLE
Implement import from GOOD dump

### PR DESCRIPTION
**Pull request by gotoAndDie**
Implemented button for importing from GOOD format inventory dumps created with [https://github.com/Andrewthe13th/Inventory_Kamera](Inventory Kamera)

Issues:
- Extra +2 Defense substat added to all artifacts with 4 substats to stop Grasscutter from adding extra substats to the artifacts
- Can't automatically increase talent level/equip weapons/artifacts
- Adding constellation doesn't work yet, even though Grasscutter's command documentation says the /give command has a constellation parameter

### CODE REVIEW

**Comment by jie65535** [comment]
Thanks for the contribution, can you send me a dump file to test?

**Comment by jie65535** [comment]
Need more testing...

**Comment by gotoAndDie** [comment]
I can send you my GOOD dump through email - please check

**Comment by jie65535** [comment]
> I can send you my GOOD dump through email - please check

Thank you. The test shows that it can be deserialized correctly. I also added progress for executing the commands.
Can you test its actual work?

_For some reasons, I can't test in the game._

---
[GrasscutterTools-v1.5.3-debug.exe.zip](https://github.com/jie65535/GrasscutterCommandGenerator/files/9125542/GrasscutterTools-v1.5.3-debug.exe.zip)

**Comment by gotoAndDie** [comment]
Just tested it - importing works with the new build

**Pull request merged**
