### PR TITLE
Waypoints & russian translation fixes (again)

### PR DESCRIPTION
**Pull request by EgorBron**
Well, this is my second contribution to GCG.
Saw **#88** a long time ago, finally got around to implementing it (yes, it's ugly, just an edited copy of Custom Commands, made in a hurry). Translations may be inaccurate and unfinished (especially in Chinese).

Also, I have again corrected some errors in Russian translation which I did not see last time.

### CODE REVIEW

**Comment by EgorBron** [comment]
p. s. I didn't implement scene ID selection

**Comment by jie65535** [comment]
I believe you have experienced the shortcomings of WinForm in this development. I am using WPF to reconstruct it and set the default language as English, which may be more convenient for functional contributions, rather than just translation.

image

I'm not ready to upload it yet, but I'm doing it. It will be a 2.0 branch.

**Comment by jie65535** [comment]
Also, the contributor @Sycamore0 is making resources related to dungeons, so I may give priority to adding this function instead of Waypoints, because we haven't collected more waypoints resources.

**Comment by EgorBron** [comment]
> 

Oh, yes, yes, WinForms very unconvenient. I'm really waiting for WPF version.

**Comment by EgorBron** [comment]
> Also, the contributor @Sycamore0 is making resources related to dungeons, so I may give priority to adding this function instead of Waypoints, because we haven't collected more waypoints resources.

Hmm, okay, I'll keep that in mind.

**Comment by jie65535** [comment]
> WinForms very unconvenient

In fact, my first release took only two days to complete. WinForms is very efficient in simple development.

**Comment by jie65535** [comment]
For this pull request, can you separate the Waypoints and other fixes into two pull requests? The Waypoints function is not ready to be added yet, but other fixes can be merged.

**Comment by EgorBron** [comment]
> For this pull request, can you separate the Waypoints and other fixes into two pull requests? The Waypoints function is not ready to be added yet, but other fixes can be merged.

Yes, I can, but not now

**Pull request closed without merging**
